import 'babel-polyfill/dist/polyfill.min.js'
import 'plyr/dist/plyr.js'
import './assets/css/meyer-reset.min.css'
import 'nouislider/distribute/nouislider.min.css'
import 'intersection-observer'
import 'font-awesome/css/font-awesome.min.css'
